export const listings = [
  {
    id: 1,
    title: "Serene Lakeside Cabin",
    location: "Nordfjord, Norway",
    price: "COP 280,000/night",
    maxGuests: 3,
    rating: 4.9,
    category: "cabins",
    featured: true,
    description: "A tranquil cabin by the fjord with mountain views, cozy interiors and private deck.",
    amenities: ["Wifi", "Fireplace", "Lake view", "Kitchen"],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511"
  },
  {
    id: 2,
    title: "Cliffside Escape",
    location: "Santorini, Greece",
    price: "COP 280,000/night",
    maxGuests: 2,
    rating: 4.9,
    category: "beachFront",
    featured: true,
    description: "A bright retreat on the cliff with sea breeze, sunset terrace and minimalist decor.",
    amenities: ["Ocean view", "Breakfast", "Air conditioning", "Pool"],
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"
  },
  {
    id: 3,
    title: "Loft Apartment",
    location: "Kyoto, Japan",
    price: "COP 280,000/night",
    maxGuests: 4,
    rating: 4.9,
    category: "citystays",
    featured: true,
    description: "Modern loft in a quiet area close to temples, cafes and local food spots.",
    amenities: ["Fast wifi", "Balcony", "Workspace", "Washer"],
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb"
  },
  {
    id: 4,
    title: "Modern Loft",
    location: "Kyoto, Japan",
    price: "COP 280,000/night",
    maxGuests: 5,
    rating: 4.9,
    category: "luxury",
    featured: true,
    description: "Refined loft with premium materials, spacious lounge and elegant city atmosphere.",
    amenities: ["Concierge", "Smart TV", "Chef kitchen", "Premium bedding"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"
  },
  {
    id: 5,
    title: "Ocean Breeze Studio",
    location: "Lisbon, Portugal",
    price: "COP 165,000/night",
    maxGuests: 2,
    rating: 4.5,
    category: "beachFront",
    featured: false,
    description: "Compact studio near the coast with natural light and walkable local neighborhoods.",
    amenities: ["Wifi", "Kitchenette", "Sea breeze balcony", "Self check-in"],
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156"
  },
  {
    id: 6,
    title: "Valley Wood Cabin",
    location: "Banff, Canada",
    price: "COP 190,000/night",
    maxGuests: 4,
    rating: 4.4,
    category: "cabins",
    featured: false,
    description: "Warm timber cabin tucked in the valley with fireplace and pine forest trails.",
    amenities: ["Fireplace", "Mountain access", "Parking", "Kitchen"],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233"
  },
  {
    id: 7,
    title: "Countryside Stone House",
    location: "Tuscany, Italy",
    price: "COP 210,000/night",
    maxGuests: 6,
    rating: 4.6,
    category: "countryside",
    featured: false,
    description: "Traditional stone home surrounded by vineyards and quiet roads.",
    amenities: ["Garden", "Outdoor dining", "Wifi", "Parking"],
    image: "https://images.unsplash.com/photo-1464890100898-a385f744067f"
  },
  {
    id: 8,
    title: "City Corner Flat",
    location: "Berlin, Germany",
    price: "COP 145,000/night",
    maxGuests: 3,
    rating: 4.3,
    category: "apartments",
    featured: false,
    description: "Simple city flat with excellent transit access and local cafes around the block.",
    amenities: ["Wifi", "Heating", "Coffee station", "Transit nearby"],
    image: "https://images.unsplash.com/photo-1493666438817-866a91353ca9"
  },
  {
    id: 9,
    title: "Blue Coast Villa",
    location: "Split, Croatia",
    price: "COP 240,000/night",
    maxGuests: 5,
    rating: 4.4,
    category: "luxury",
    featured: false,
    description: "A refined villa with open terrace and calm blue-hued interior palette.",
    amenities: ["Private terrace", "Pool", "Sea view", "Wifi"],
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858"
  },
  {
    id: 10,
    title: "Harbor Light Apartment",
    location: "Valparaiso, Chile",
    price: "COP 135,000/night",
    maxGuests: 2,
    rating: 4.2,
    category: "apartments",
    featured: false,
    description: "Colorful apartment close to the harbor with panoramic city viewpoints.",
    amenities: ["Wifi", "City view", "Kitchen", "Late check-in"],
    image: "https://images.unsplash.com/photo-1505692952047-1a78307da8f2"
  },
  {
    id: 11,
    title: "Forest Edge Cabin",
    location: "Asheville, USA",
    price: "COP 175,000/night",
    maxGuests: 4,
    rating: 4.3,
    category: "cabins",
    featured: false,
    description: "Minimal rustic cabin with woodland views and fresh mountain air.",
    amenities: ["Fire pit", "Wifi", "Patio", "Kitchen"],
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607"
  },
  {
    id: 12,
    title: "Dune View Retreat",
    location: "Essaouira, Morocco",
    price: "COP 160,000/night",
    maxGuests: 3,
    rating: 4.4,
    category: "beachFront",
    featured: false,
    description: "Soft-toned retreat near dunes and ocean with breezy indoor-outdoor spaces.",
    amenities: ["Terrace", "Breakfast", "Wifi", "Beach access"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"
  },
  {
    id: 13,
    title: "Olive Grove House",
    location: "Seville, Spain",
    price: "COP 170,000/night",
    maxGuests: 5,
    rating: 4.5,
    category: "countryside",
    featured: false,
    description: "Peaceful farmhouse setting surrounded by olive trees and warm sunsets.",
    amenities: ["Garden", "Wifi", "Parking", "Outdoor lounge"],
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef"
  },
  {
    id: 14,
    title: "Skyline Premium Suite",
    location: "Dubai, UAE",
    price: "COP 260,000/night",
    maxGuests: 3,
    rating: 4.6,
    category: "hotels",
    featured: false,
    description: "Stylish high-rise suite with skyline views and high-end hotel-style services.",
    amenities: ["Gym", "Pool", "24h reception", "Smart room"],
    image: "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a"
  }
];