// Lightweight list of country calling codes for the phone selector.
// Includes common countries and a fallback "Other" option.
const phoneCodes = [
  { iso: "US", code: "+1", label: "United States (+1)" },
  { iso: "CA", code: "+1", label: "Canada (+1)" },
  { iso: "MX", code: "+52", label: "Mexico (+52)" },
  { iso: "CO", code: "+57", label: "Colombia (+57)" },
  { iso: "AR", code: "+54", label: "Argentina (+54)" },
  { iso: "CL", code: "+56", label: "Chile (+56)" },
  { iso: "PE", code: "+51", label: "Peru (+51)" },
  { iso: "VE", code: "+58", label: "Venezuela (+58)" },
  { iso: "BR", code: "+55", label: "Brazil (+55)" },
  { iso: "GB", code: "+44", label: "United Kingdom (+44)" },
  { iso: "ES", code: "+34", label: "Spain (+34)" },
  { iso: "FR", code: "+33", label: "France (+33)" },
  { iso: "DE", code: "+49", label: "Germany (+49)" },
  { iso: "IT", code: "+39", label: "Italy (+39)" },
  { iso: "IN", code: "+91", label: "India (+91)" },
  { iso: "CN", code: "+86", label: "China (+86)" },
  { iso: "JP", code: "+81", label: "Japan (+81)" },
  { iso: "AU", code: "+61", label: "Australia (+61)" },
  { iso: "NZ", code: "+64", label: "New Zealand (+64)" },
  { iso: "NL", code: "+31", label: "Netherlands (+31)" },
  { iso: "BE", code: "+32", label: "Belgium (+32)" },
  { iso: "DK", code: "+45", label: "Denmark (+45)" },
  { iso: "NO", code: "+47", label: "Norway (+47)" },
  { iso: "SE", code: "+46", label: "Sweden (+46)" },
  { iso: "UA", code: "+380", label: "Ukraine (+380)" },
  { iso: "RU", code: "+7", label: "Russia (+7)" },
  { iso: "SA", code: "+966", label: "Saudi Arabia (+966)" },
  { iso: "EG", code: "+20", label: "Egypt (+20)" },
  { iso: "NG", code: "+234", label: "Nigeria (+234)" },
  { iso: "ZA", code: "+27", label: "South Africa (+27)" },
  { iso: "PH", code: "+63", label: "Philippines (+63)" },
  { iso: "KR", code: "+82", label: "South Korea (+82)" },
  { iso: "IE", code: "+353", label: "Ireland (+353)" },
  { iso: "PT", code: "+351", label: "Portugal (+351)" },
  { iso: "PL", code: "+48", label: "Poland (+48)" },
  { iso: "CZ", code: "+420", label: "Czech Republic (+420)" },
  { iso: "FI", code: "+358", label: "Finland (+358)" },
  { iso: "CH", code: "+41", label: "Switzerland (+41)" },
  { iso: null, code: "other", label: "Otro / Otro código" }
];

export default phoneCodes;
